// <auto-generated />
using System;
using DentalClinicProject.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DentalClinicProject.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260324160647_AddStockProduct")]
    partial class AddStockProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Arabic_CI_AI")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DentalClinicProject.Core.Entities.AuthModel.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExaminationEppointment")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("DoctorId", "ExaminationEppointment")
                        .IsUnique();

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateOnly(2024, 1, 25),
                            DoctorId = 1,
                            ExaminationEppointment = new DateTime(2024, 2, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            PatientId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateOnly(2024, 1, 26),
                            DoctorId = 2,
                            ExaminationEppointment = new DateTime(2024, 2, 5, 14, 0, 0, 0, DateTimeKind.Utc),
                            PatientId = 2,
                            ServiceId = 2
                        });
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateOnly(2024, 1, 20),
                            UserId = "patient-1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateOnly(2024, 1, 22),
                            UserId = "user-1"
                        });
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CartId = 1,
                            CreatedAt = new DateOnly(2026, 3, 24),
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 350m
                        },
                        new
                        {
                            Id = 2,
                            CartId = 1,
                            CreatedAt = new DateOnly(2026, 3, 24),
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 80m
                        },
                        new
                        {
                            Id = 3,
                            CartId = 2,
                            CreatedAt = new DateOnly(2026, 3, 24),
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 45m
                        },
                        new
                        {
                            Id = 4,
                            CartId = 2,
                            CreatedAt = new DateOnly(2026, 3, 24),
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 120m
                        });
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeliveryDate = new DateTime(2026, 4, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DeliveryId = 1,
                            Status = "Completed",
                            UserId = "user-1"
                        },
                        new
                        {
                            Id = 2,
                            DeliveryDate = new DateTime(2026, 4, 6, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DeliveryId = 2,
                            Status = "Pending",
                            UserId = "user-1"
                        });
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            Price = 350m,
                            ProductId = 1,
                            ProductName = "Electric Toothbrush",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 2,
                            Price = 80m,
                            ProductId = 2,
                            ProductName = "Medical Toothpaste",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            Price = 45m,
                            ProductId = 3,
                            ProductName = "Dental Floss",
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasFilter("[Status] = 'Paid'");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasFilter("[TransactionId] IS NOT NULL");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 350m,
                            Currency = "EGP",
                            CustomerId = "user-1",
                            Description = "Payment for Order #1 - Electric Toothbrush",
                            OrderId = 1,
                            PaidAt = new DateTime(2024, 1, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "CreditCard",
                            Status = "Paid",
                            TransactionId = "TXN-2024-001-ORDER-1"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 160m,
                            Currency = "EGP",
                            CustomerId = "user-1",
                            Description = "Payment for Order #2 - Medical Toothpaste x2",
                            OrderId = 2,
                            PaidAt = new DateTime(2024, 1, 20, 14, 15, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "Cash",
                            Status = "Refunded",
                            TransactionId = "TXN-2024-002-ORDER-2"
                        });
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateOnly(2024, 1, 25),
                            Description = "Advanced electric toothbrush with 3 cleaning modes",
                            Name = "Electric Toothbrush",
                            Price = 350m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateOnly(2024, 1, 25),
                            Description = "Medical toothpaste for sensitive teeth",
                            Name = "Medical Toothpaste",
                            Price = 80m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateOnly(2024, 1, 25),
                            Description = "Mint flavored dental floss",
                            Name = "Dental Floss",
                            Price = 45m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateOnly(2024, 1, 25),
                            Description = "Antibacterial mouthwash",
                            Name = "Mouthwash",
                            Price = 120m,
                            Stock = 0
                        });
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.Rate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rates");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Rate");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateOnly(2024, 2, 2),
                            DurationInMinutes = 30,
                            Name = "General Checkup",
                            Price = 200m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateOnly(2024, 2, 6),
                            DurationInMinutes = 45,
                            Name = "Teeth Cleaning",
                            Price = 300m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateOnly(2024, 2, 6),
                            DurationInMinutes = 60,
                            Name = "Dental Filling",
                            Price = 500m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateOnly(2024, 2, 6),
                            DurationInMinutes = 30,
                            Name = "Tooth Extraction",
                            Price = 400m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateOnly(2024, 2, 6),
                            DurationInMinutes = 90,
                            Name = "Teeth Whitening",
                            Price = 1500m
                        });
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Users.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = "admin-1",
                            CreatedAt = new DateOnly(2024, 1, 1)
                        });
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Users.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ADMIN-CONCURRENCY-001",
                            Email = "admin@dentalclinic.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "Dental",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@DENTALCLINIC.COM",
                            NormalizedUserName = "ADMIN@DENTALCLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGorgtN1aWOwuhiQlRZuNa7oimeAFA8ZS+yb3u8Qc+C+x3MipZNNNIhOi5bl/1ws+Q==",
                            PhoneNumberConfirmed = false,
                            Provider = "Local",
                            ProviderId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            SecurityStamp = "QURNSU5TRUNVUklUWVNUQU1QMDA=",
                            TwoFactorEnabled = false,
                            UserName = "adminUsername"
                        },
                        new
                        {
                            Id = "doctor-1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "DOCTOR1-CONCURRENCY-001",
                            Email = "doctor1@dentalclinic.com",
                            EmailConfirmed = true,
                            FirstName = "Sarah",
                            LastName = "Ali",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR1@DENTALCLINIC.COM",
                            NormalizedUserName = "DOCTOR1@DENTALCLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEA6LlozjK/8AFKsEUcoc0URf8Kc3fYa8bLsw6H5+lOvxvwmCGU65CSzZYe3DiUlc1Q==",
                            PhoneNumberConfirmed = false,
                            Provider = "Local",
                            ProviderId = "b2c3d4e5-f6a7-8901-bcde-f12345678901",
                            SecurityStamp = "RE9DVE9SMVNFQ1VSSVRZU1RBTVA=",
                            TwoFactorEnabled = false,
                            UserName = "doctorUsername1"
                        },
                        new
                        {
                            Id = "doctor-2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "DOCTOR2-CONCURRENCY-001",
                            Email = "doctor2@dentalclinic.com",
                            EmailConfirmed = true,
                            FirstName = "Mahmoud",
                            LastName = "Hassan",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR2@DENTALCLINIC.COM",
                            NormalizedUserName = "DOCTOR2@DENTALCLINIC.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIJreR46lGQQQ5gUg3tr2IJZisZshIYLvut+kz5WqIo2zwKjv9NYrZS9xHAhm1k8Bg==",
                            PhoneNumberConfirmed = false,
                            Provider = "Local",
                            ProviderId = "c3d4e5f6-a7b8-9012-cdef-123456789012",
                            SecurityStamp = "RE9DVE9SMlNFQ1VSSVRZU1RBTVA=",
                            TwoFactorEnabled = false,
                            UserName = "doctorUsername2"
                        },
                        new
                        {
                            Id = "patient-1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "PATIENT1-CONCURRENCY-001",
                            Email = "patient1@example.com",
                            EmailConfirmed = true,
                            FirstName = "Fatima",
                            LastName = "Ahmed",
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT1@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT1@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ/gwoGWiEdWFdk8LsAh1dfUvAu/9GGa3ebgbXpWPWhXjnsXRm0DQ8nLKq/yi55LcA==",
                            PhoneNumberConfirmed = false,
                            Provider = "Local",
                            ProviderId = "d4e5f6a7-b8c9-0123-def1-234567890123",
                            SecurityStamp = "UEFUSUVOVDFTRUNTVVJJVFVTVEFNUA==",
                            TwoFactorEnabled = false,
                            UserName = "patient1@example.com"
                        },
                        new
                        {
                            Id = "patient-2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "PATIENT2-CONCURRENCY-001",
                            Email = "patient2@example.com",
                            EmailConfirmed = true,
                            FirstName = "Khaled",
                            LastName = "Abdullah",
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT2@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT2@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMk3DV11DFvB+aKgUbP3Q84O++hoXTi1I9ikkt+Via2Rr4VsZHLyvWWw9yUMRQghcg==",
                            PhoneNumberConfirmed = false,
                            Provider = "Local",
                            ProviderId = "e5f6a7b8-c9d0-1234-ef12-345678901234",
                            SecurityStamp = "UEFUSUVOVDJTRUNTVVJJVFVTVEFNUA==",
                            TwoFactorEnabled = false,
                            UserName = "patient2@example.com"
                        },
                        new
                        {
                            Id = "user-1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "USER-CONCURRENCY-001",
                            Email = "user@example.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@EXAMPLE.COM",
                            NormalizedUserName = "USER@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDXDYwydBslF+l+wymoQRV0AhyxRvN5QbAWsAjeGBTb/wHqEv8TlM7PT3h08apHLdQ==",
                            PhoneNumberConfirmed = false,
                            Provider = "Local",
                            ProviderId = "f6a7b8c9-d0e1-2345-f123-456789012345",
                            SecurityStamp = "VVNFUlNFQ1VSSVRZU1RBTVA=",
                            TwoFactorEnabled = false,
                            UserName = "user@example.com"
                        },
                        new
                        {
                            Id = "delivery-1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "DELIVERY1-CONCURRENCY-001",
                            Email = "delivery@dentalclinic.com",
                            EmailConfirmed = true,
                            FirstName = "Ahmed",
                            LastName = "Elsayed",
                            LockoutEnabled = false,
                            NormalizedEmail = "DEKIVERY1@DENTALCLINIC.COM",
                            NormalizedUserName = "DELIVERYUSERNAME1",
                            PasswordHash = "AQAAAAIAAYagAAAAEDXDYwydBslF+l+wymoQRV0AhyxRvN5QbAWsAjeGBTb/wHqEv8TlM7PT3h08apHLdQ==",
                            PhoneNumberConfirmed = false,
                            Provider = "Local",
                            ProviderId = "b2c3d4e5-f6a7-8901-qwer-f12345678901",
                            SecurityStamp = "RE9DVE9SMVNFQ1VSSVRZU1RBTVA=",
                            TwoFactorEnabled = false,
                            UserName = "deliveryUsername1"
                        },
                        new
                        {
                            Id = "delivery-2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "DELIVERY2-CONCURRENCY-001",
                            Email = "delivery2@dentalclinic.com",
                            EmailConfirmed = true,
                            FirstName = "Mahmoud",
                            LastName = "Hassan",
                            LockoutEnabled = false,
                            NormalizedEmail = "DELIVERY2@DENTALCLINIC.COM",
                            NormalizedUserName = "DELIVERYUSERNAME2",
                            PasswordHash = "AQAAAAIAAYagAAAAEDXDYwydBslF+l+wymoQRV0AhyxRvN5QbAWsAjeGBTb/wHqEv8TlM7PT3h08apHLdQ==",
                            PhoneNumberConfirmed = false,
                            Provider = "Local",
                            ProviderId = "c3d4e5f6-a7b8-9012-asdf-123456789012",
                            SecurityStamp = "RE9DVE9SMlNFQ1VSSVRZU1RBTVA=",
                            TwoFactorEnabled = false,
                            UserName = "deliveryUsername2"
                        });
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Users.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CapactiyOfDay")
                        .HasColumnType("int");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("ReasonForRejection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Deliveries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = "delivery-1",
                            CapactiyOfDay = 10,
                            CreatedAt = new DateOnly(2024, 1, 5),
                            IsApproved = true,
                            Salary = 15000m
                        },
                        new
                        {
                            Id = 2,
                            AppUserId = "delivery-2",
                            CapactiyOfDay = 8,
                            CreatedAt = new DateOnly(2024, 1, 10),
                            IsApproved = false,
                            ReasonForRejection = "He did not submit the required documents.",
                            Salary = 0.0m
                        });
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Users.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CapactiyOfDay")
                        .HasColumnType("int");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("ReasonForRejection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = "doctor-1",
                            CapactiyOfDay = 10,
                            CreatedAt = new DateOnly(2024, 1, 5),
                            IsApproved = true,
                            Salary = 15000m
                        },
                        new
                        {
                            Id = 2,
                            AppUserId = "doctor-2",
                            CapactiyOfDay = 8,
                            CreatedAt = new DateOnly(2024, 1, 10),
                            IsApproved = false,
                            ReasonForRejection = "He did not submit the required documents.",
                            Salary = 0.0m
                        });
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Users.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.HasIndex("DoctorId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = "patient-1",
                            CreatedAt = new DateOnly(2024, 1, 15),
                            DoctorId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppUserId = "patient-2",
                            CreatedAt = new DateOnly(2024, 1, 18),
                            DoctorId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.AppointmentRate", b =>
                {
                    b.HasBaseType("DentalClinicProject.Core.Entities.Core.Rate");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.HasIndex("AppointmentId");

                    b.HasDiscriminator().HasValue("AppointmentRate");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Comment = "Good service overall",
                            CreatedAt = new DateOnly(2024, 2, 2),
                            UserId = "patient-1",
                            Value = 4,
                            AppointmentId = 1
                        });
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.DoctorRate", b =>
                {
                    b.HasBaseType("DentalClinicProject.Core.Entities.Core.Rate");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.HasIndex("DoctorId");

                    b.HasIndex("UserId", "DoctorId")
                        .IsUnique()
                        .HasFilter("[DoctorId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("DoctorRate");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Comment = "Excellent service and very professional doctor",
                            CreatedAt = new DateOnly(2024, 2, 2),
                            UserId = "patient-1",
                            Value = 3,
                            DoctorId = 1
                        });
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.ProductRate", b =>
                {
                    b.HasBaseType("DentalClinicProject.Core.Entities.Core.Rate");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasIndex("ProductId");

                    b.HasDiscriminator().HasValue("ProductRate");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Good service overall",
                            CreatedAt = new DateOnly(2024, 2, 2),
                            UserId = "patient-1",
                            Value = 4,
                            ProductId = 1
                        });
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.AuthModel.RefreshToken", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Users.AppUser", "AppUser")
                        .WithOne()
                        .HasForeignKey("DentalClinicProject.Core.Entities.AuthModel.RefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.Appointment", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Users.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DentalClinicProject.Core.Entities.Users.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DentalClinicProject.Core.Entities.Core.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.Cart", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Users.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.CartItem", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Core.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DentalClinicProject.Core.Entities.Core.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.Order", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Users.Delivery", "Delivery")
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DentalClinicProject.Core.Entities.Users.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.OrderItem", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Core.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DentalClinicProject.Core.Entities.Core.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.Payment", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Core.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Users.Admin", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Users.AppUser", "AppUser")
                        .WithOne()
                        .HasForeignKey("DentalClinicProject.Core.Entities.Users.Admin", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Users.Delivery", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Users.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Users.Doctor", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Users.AppUser", "AppUser")
                        .WithOne()
                        .HasForeignKey("DentalClinicProject.Core.Entities.Users.Doctor", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Users.Patient", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Users.AppUser", "AppUser")
                        .WithOne()
                        .HasForeignKey("DentalClinicProject.Core.Entities.Users.Patient", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DentalClinicProject.Core.Entities.Users.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AppUser");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DentalClinicProject.Core.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.AppointmentRate", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Core.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.DoctorRate", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Users.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.ProductRate", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Core.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.Product", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Users.Delivery", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Users.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
