// <auto-generated />
using System;
using DentalClinicProject.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DentalClinicProject.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260218084338_EditDataType")]
    partial class EditDataType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Arabic_CI_AI")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DentalClinicProject.Core.Entities.AuthModel.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExaminationEppointment")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ServiceId")
                        .IsUnique();

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateOnly(2024, 1, 25),
                            DoctorId = 1,
                            ExaminationEppointment = new DateTime(2024, 2, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            PatientId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateOnly(2024, 1, 26),
                            DoctorId = 2,
                            ExaminationEppointment = new DateTime(2024, 2, 5, 14, 0, 0, 0, DateTimeKind.Utc),
                            PatientId = 2,
                            ServiceId = 2
                        });
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 350m,
                            Currency = "EGP",
                            CustomerId = "user-1",
                            Description = "Purchase of Electric Toothbrush",
                            PaymentDate = new DateTime(2024, 1, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "Credit Card",
                            ProductId = 1,
                            Status = "Paid",
                            TransactionId = "TXN-2024-001-ELECTRIC-BRUSH"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 80m,
                            Currency = "EGP",
                            CustomerId = "user-1",
                            Description = "Purchase of Medical Toothpaste",
                            PaymentDate = new DateTime(2024, 1, 20, 14, 15, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "Cash",
                            ProductId = 2,
                            Status = "Refunded",
                            TransactionId = "TXN-2024-002-TOOTHPASTE"
                        });
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateOnly(2024, 1, 25),
                            Description = "Advanced electric toothbrush with 3 cleaning modes",
                            Name = "Electric Toothbrush",
                            Price = 350m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateOnly(2024, 1, 26),
                            Description = "Medical toothpaste for sensitive teeth",
                            Name = "Medical Toothpaste",
                            Price = 80m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateOnly(2024, 1, 26),
                            Description = "Mint flavored dental floss",
                            Name = "Dental Floss",
                            Price = 45m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateOnly(2024, 1, 26),
                            Description = "Antibacterial mouthwash",
                            Name = "Mouthwash",
                            Price = 120m
                        });
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.Rate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("DoctorId")
                        .IsUnique();

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Rates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            Comment = "Excellent service and very professional doctor",
                            CreatedAt = new DateOnly(2024, 2, 2),
                            DoctorId = 1,
                            ProductId = 1,
                            Value = 3
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 2,
                            Comment = "Good service overall",
                            CreatedAt = new DateOnly(2024, 2, 6),
                            DoctorId = 2,
                            ProductId = 2,
                            Value = 2
                        });
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateOnly(2024, 2, 2),
                            DurationInMinutes = 30,
                            Name = "General Checkup",
                            Price = 200m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateOnly(2024, 2, 6),
                            DurationInMinutes = 45,
                            Name = "Teeth Cleaning",
                            Price = 300m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateOnly(2024, 2, 6),
                            DurationInMinutes = 60,
                            Name = "Dental Filling",
                            Price = 500m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateOnly(2024, 2, 6),
                            DurationInMinutes = 30,
                            Name = "Tooth Extraction",
                            Price = 400m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateOnly(2024, 2, 6),
                            DurationInMinutes = 90,
                            Name = "Teeth Whitening",
                            Price = 1500m
                        });
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Users.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = "admin-1",
                            CreatedAt = new DateOnly(2024, 1, 1)
                        });
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Users.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ADMIN-CONCURRENCY-001",
                            Email = "admin@dentalclinic.com",
                            EmailConfirmed = true,
                            FirstName = "Ahmed",
                            LastName = "Mohamed",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@DENTALCLINIC.COM",
                            NormalizedUserName = "ADMIN@DENTALCLINIC.COM",
                            PasswordHash = "$2a$12$PIsynfBEoxgQeX.9b1NhK.42bvqcU4z0m6RdOJK1SobWfVPSsx1EO",
                            PhoneNumberConfirmed = false,
                            Provider = "Local",
                            ProviderId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            SecurityStamp = "ADMIN-SECURITY-STAMP-001",
                            TwoFactorEnabled = false,
                            UserName = "admin@dentalclinic.com"
                        },
                        new
                        {
                            Id = "doctor-1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "DOCTOR1-CONCURRENCY-001",
                            Email = "doctor1@dentalclinic.com",
                            EmailConfirmed = true,
                            FirstName = "Sarah",
                            LastName = "Ali",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR1@DENTALCLINIC.COM",
                            NormalizedUserName = "DOCTOR1@DENTALCLINIC.COM",
                            PasswordHash = "$2a$12$ItcpdkqaPFmWpAG6LVkGKu8qUspXV7sz4phOKrdAPQtcVN/hPb.tK",
                            PhoneNumberConfirmed = false,
                            Provider = "Local",
                            ProviderId = "b2c3d4e5-f6a7-8901-bcde-f12345678901",
                            SecurityStamp = "DOCTOR1-SECURITY-STAMP-001",
                            TwoFactorEnabled = false,
                            UserName = "doctor1@dentalclinic.com"
                        },
                        new
                        {
                            Id = "doctor-2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "DOCTOR2-CONCURRENCY-001",
                            Email = "doctor2@dentalclinic.com",
                            EmailConfirmed = true,
                            FirstName = "Mahmoud",
                            LastName = "Hassan",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR2@DENTALCLINIC.COM",
                            NormalizedUserName = "DOCTOR2@DENTALCLINIC.COM",
                            PasswordHash = "$2a$12$ItcpdkqaPFmWpAG6LVkGKu8qUspXV7sz4phOKrdAPQtcVN/hPb.tK",
                            PhoneNumberConfirmed = false,
                            Provider = "Local",
                            ProviderId = "c3d4e5f6-a7b8-9012-cdef-123456789012",
                            SecurityStamp = "DOCTOR2-SECURITY-STAMP-001",
                            TwoFactorEnabled = false,
                            UserName = "doctor2@dentalclinic.com"
                        },
                        new
                        {
                            Id = "patient-1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "PATIENT1-CONCURRENCY-001",
                            Email = "patient1@example.com",
                            EmailConfirmed = true,
                            FirstName = "Fatima",
                            LastName = "Ahmed",
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT1@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT1@EXAMPLE.COM",
                            PasswordHash = "$2a$12$zFq7IDP.u8zUtqmlrBD55upoDjQFjAn9iPdRNfK95t0rg1fpIwh6S",
                            PhoneNumberConfirmed = false,
                            Provider = "Local",
                            ProviderId = "d4e5f6a7-b8c9-0123-def1-234567890123",
                            SecurityStamp = "PATIENT1-SECURITY-STAMP-001",
                            TwoFactorEnabled = false,
                            UserName = "patient1@example.com"
                        },
                        new
                        {
                            Id = "patient-2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "PATIENT2-CONCURRENCY-001",
                            Email = "patient2@example.com",
                            EmailConfirmed = true,
                            FirstName = "Khaled",
                            LastName = "Abdullah",
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT2@EXAMPLE.COM",
                            NormalizedUserName = "PATIENT2@EXAMPLE.COM",
                            PasswordHash = "$2a$12$zFq7IDP.u8zUtqmlrBD55upoDjQFjAn9iPdRNfK95t0rg1fpIwh6S",
                            PhoneNumberConfirmed = false,
                            Provider = "Local",
                            ProviderId = "e5f6a7b8-c9d0-1234-ef12-345678901234",
                            SecurityStamp = "PATIENT2-SECURITY-STAMP-001",
                            TwoFactorEnabled = false,
                            UserName = "patient2@example.com"
                        },
                        new
                        {
                            Id = "user-1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "USER-CONCURRENCY-001",
                            Email = "user@example.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@EXAMPLE.COM",
                            NormalizedUserName = "USER@EXAMPLE.COM",
                            PasswordHash = "$2a$12$vymAZaoE/iWWVCwN1Cp3DueGCpKrkt3QtrXosVVylxPFSJ31p7a7S",
                            PhoneNumberConfirmed = false,
                            Provider = "Local",
                            ProviderId = "f6a7b8c9-d0e1-2345-f123-456789012345",
                            SecurityStamp = "USER-SECURITY-STAMP-001",
                            TwoFactorEnabled = false,
                            UserName = "user@example.com"
                        });
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Users.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CapactiyOfDay")
                        .HasColumnType("int");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("ReasonForRejection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = "doctor-1",
                            CapactiyOfDay = 10,
                            CreatedAt = new DateOnly(2024, 1, 5),
                            IsApproved = true,
                            Salary = 15000m
                        },
                        new
                        {
                            Id = 2,
                            AppUserId = "doctor-2",
                            CapactiyOfDay = 8,
                            CreatedAt = new DateOnly(2024, 1, 10),
                            IsApproved = false,
                            ReasonForRejection = "He did not submit the required documents.",
                            Salary = 0.0m
                        });
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Users.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.HasIndex("DoctorId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = "patient-1",
                            CreatedAt = new DateOnly(2024, 1, 15),
                            DoctorId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppUserId = "patient-2",
                            CreatedAt = new DateOnly(2024, 1, 18),
                            DoctorId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin",
                            ConcurrencyStamp = "ROLE-ADMIN-001",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "role-doctor",
                            ConcurrencyStamp = "ROLE-DOCTOR-001",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = "role-patient",
                            ConcurrencyStamp = "ROLE-PATIENT-001",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        },
                        new
                        {
                            Id = "role-user",
                            ConcurrencyStamp = "ROLE-USER-001",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.AuthModel.RefreshToken", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Users.AppUser", "AppUser")
                        .WithOne()
                        .HasForeignKey("DentalClinicProject.Core.Entities.AuthModel.RefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.Appointment", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Users.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DentalClinicProject.Core.Entities.Users.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DentalClinicProject.Core.Entities.Core.Service", "Service")
                        .WithOne()
                        .HasForeignKey("DentalClinicProject.Core.Entities.Core.Appointment", "ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.Payment", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Core.Product", "Product")
                        .WithOne("Payment")
                        .HasForeignKey("DentalClinicProject.Core.Entities.Core.Payment", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.Rate", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Core.Appointment", "Appointment")
                        .WithOne()
                        .HasForeignKey("DentalClinicProject.Core.Entities.Core.Rate", "AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DentalClinicProject.Core.Entities.Users.Doctor", "Doctor")
                        .WithOne()
                        .HasForeignKey("DentalClinicProject.Core.Entities.Core.Rate", "DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DentalClinicProject.Core.Entities.Core.Product", "Product")
                        .WithOne()
                        .HasForeignKey("DentalClinicProject.Core.Entities.Core.Rate", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Users.Admin", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Users.AppUser", "AppUser")
                        .WithOne()
                        .HasForeignKey("DentalClinicProject.Core.Entities.Users.Admin", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Users.Doctor", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Users.AppUser", "AppUser")
                        .WithOne()
                        .HasForeignKey("DentalClinicProject.Core.Entities.Users.Doctor", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Users.Patient", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Users.AppUser", "AppUser")
                        .WithOne()
                        .HasForeignKey("DentalClinicProject.Core.Entities.Users.Patient", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DentalClinicProject.Core.Entities.Users.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AppUser");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DentalClinicProject.Core.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DentalClinicProject.Core.Entities.Users.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Core.Product", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("DentalClinicProject.Core.Entities.Users.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
